"""
Tests for generator.renderers.rest_renderer.RestRenderer - Phase 1.1
"""

from pathlib import Path

import pytest

from generator.renderers.rest_renderer import RestRenderer

VALID_SPEC: dict = {
    "service": {"name": "my-service", "type": "rest"},
    "http": {"inbound": {"path": "/hello", "method": "GET"}},
    "integration": {
        "target_type": "rest",
        "base_url": "https://backend.example.com",
        "endpoint_path": "/api/v1",
    },
}

FULL_SPEC: dict = {
    "service": {
        "name": "full-service",
        "type": "rest",
        "description": "Full spec service",
    },
    "http": {"inbound": {"path": "/full", "method": "POST"}},
    "integration": {
        "target_type": "rest",
        "base_url": "https://full.example.com",
        "endpoint_path": "/v2",
        "mock_enabled": False,
    },
}


# ---------- directory structure ----------

def test_render_creates_service_directory(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service").is_dir()


def test_render_creates_app_main_py(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "app" / "main.py").is_file()


def test_render_creates_app_api_inbound(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "app" / "api" / "inbound.py").is_file()


def test_render_creates_domain_files(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    base = tmp_path / "my-service" / "app" / "domain"
    assert (base / "dme_input.py").is_file()
    assert (base / "backend_payload.py").is_file()


def test_render_creates_services_mapper(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "app" / "services" / "mapper.py").is_file()


def test_render_creates_integrations_outbound(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "app" / "integrations" / "outbound_rest.py").is_file()


def test_render_creates_settings_files(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    base = tmp_path / "my-service"
    assert (base / "settings.dev.yml").is_file()
    assert (base / "settings.hml.yml").is_file()
    assert (base / "settings.prod.yml").is_file()


def test_render_creates_requirements_txt(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "requirements.txt").is_file()


def test_render_creates_readme(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    assert (tmp_path / "my-service" / "README.md").is_file()


# ---------- placeholder replacement ----------

def test_placeholder_service_name_replaced(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "main.py").read_text()
    assert "my-service" in content
    assert "{{ service_name }}" not in content


def test_placeholder_http_method_lower_replaced(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "api" / "inbound.py").read_text()
    assert "@router.get(" in content
    assert "{{ http_method_lower }}" not in content


def test_placeholder_inbound_path_replaced(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "api" / "inbound.py").read_text()
    assert '"/hello"' in content
    assert "{{ inbound_path }}" not in content


def test_placeholder_backend_url_replaced_in_outbound(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "integrations" / "outbound_rest.py").read_text()
    assert "https://backend.example.com/api/v1" in content
    assert "{{ backend_base_url }}" not in content
    assert "{{ backend_endpoint_path }}" not in content


def test_no_placeholders_remain_in_any_file(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    service_dir = tmp_path / "my-service"
    for f in service_dir.rglob("*"):
        if f.is_file() and f.suffix in {".py", ".txt", ".md", ".yml"}:
            content = f.read_text()
            assert "{{" not in content, f"Unreplaced placeholder found in {f}"


# ---------- optional field defaults ----------

def test_default_description_used_when_omitted(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "main.py").read_text()
    assert "Generated by ipiranga-python-integration-factory" in content


def test_default_mock_enabled_is_true(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "app" / "integrations" / "outbound_rest.py").read_text()
    assert "MOCK_ENABLED: bool = True" in content


def test_explicit_mock_enabled_false_rendered(tmp_path: Path) -> None:
    RestRenderer(FULL_SPEC).render(str(tmp_path))
    content = (tmp_path / "full-service" / "app" / "integrations" / "outbound_rest.py").read_text()
    assert "MOCK_ENABLED: bool = False" in content


def test_explicit_description_rendered(tmp_path: Path) -> None:
    RestRenderer(FULL_SPEC).render(str(tmp_path))
    content = (tmp_path / "full-service" / "app" / "main.py").read_text()
    assert "Full spec service" in content


# ---------- settings files ----------

def test_settings_dev_contains_service_name(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    content = (tmp_path / "my-service" / "settings.dev.yml").read_text()
    assert "name: my-service" in content


def test_settings_files_identical_content(tmp_path: Path) -> None:
    RestRenderer(VALID_SPEC).render(str(tmp_path))
    base = tmp_path / "my-service"
    dev = (base / "settings.dev.yml").read_text()
    hml = (base / "settings.hml.yml").read_text()
    prod = (base / "settings.prod.yml").read_text()
    assert dev == hml == prod


# ---------- overwrite protection ----------

def test_render_fails_if_destination_exists(tmp_path: Path) -> None:
    (tmp_path / "my-service").mkdir()
    with pytest.raises(FileExistsError, match="already exists"):
        RestRenderer(VALID_SPEC).render(str(tmp_path))
